# WANDB PARAMS
"PROJECT": "housemaze"
"ENV_NAME": "housemaze"
"TOTAL_TIMESTEPS": 1_500_000
"TRAINING_INTERVAL": 5

"EMBED_HIDDEN_DIM": 64
"NUM_MLP_LAYERS": 0
"NUM_EMBED_LAYERS": 0
"MLP_HIDDEN_DIM": 512
"AGENT_RNN_DIM": 256
"ACTIVATION": 'leaky_relu'
"NUM_Q_LAYERS": 2


'exp': 'maze1_all'