# WANDB PARAMS
"PROJECT": "housemaze"
"ENV_NAME": "housemaze"
"TOTAL_TIMESTEPS": 1_500_000
"TRAINING_INTERVAL": 5

"EMBED_HIDDEN_DIM": 64
"NUM_EMBED_LAYERS": 0
"NUM_MLP_LAYERS": 0
"AGENT_RNN_DIM": 256
"ACTIVATION": 'leaky_relu'

'exp': 'exp1'