ALG: 'pqn'

# EXPERIMENT PARAMS
NUM_SEEDS: 1
SEED: 1

# logggin
MAX_EPISODE_LOG_LEN: 40


# RUN PARAMS
EVAL_STEPS: 100
EVAL_EPISODES: 100
LEARNER_LOG_PERIOD: 500
LEARNER_EXTRA_LOG_PERIOD: 5_000
EVAL_LOG_PERIOD: 25
EVAL_LOG_PERIOD_ACTOR: 0
GRADIENT_LOG_PERIOD: 5_000

# NEURAL NET PARAMS
EMBED_HIDDEN_DIM: 64
NUM_MLP_LAYERS: 0
NUM_EMBED_LAYERS: 0
MLP_HIDDEN_DIM: 256
AGENT_RNN_DIM: 256
ACTIVATION: 'leaky_relu'
NUM_Q_LAYERS: 2
NORM_TYPE: 'layer_norm'
NORM_QFN: 'layer_norm'

# LEARN PARAMS
BATCH_SIZE: 131072
TRAINING_INTERVAL: 128
NUM_EPOCHS: 4
NUM_MINIBATCHES: 4

# epsilon-greedy
FIXED_EPSILON: 2 # range of epsilons
EPSILON_START: 1.0
EPSILON_FINISH: 0.1
EPSILON_ANNEAL_TIME: 5e5
MAX_GRAD_NORM: 80

# ALGOO
LR: 0.001
NUM_UPDATES_DECAY: 
LR_LINEAR_DECAY: True
EPS_ADAM: 1e-8

GAMMA: 0.99
