ALG: 'pqn'

# EXPERIMENT PARAMS
NUM_SEEDS: 1
SEED: 1

# logggin
MAX_EPISODE_LOG_LEN: 40


# RUN PARAMS
TOTAL_TIMESTEPS: 5e5
EVAL_STEPS: 100
EVAL_EPISODES: 100
LEARNER_LOG_PERIOD: 50
LEARNER_EXTRA_LOG_PERIOD: 100
EVAL_LOG_PERIOD: 5
EVAL_LOG_PERIOD_ACTOR: 0
GRADIENT_LOG_PERIOD: 50

# NEURAL NET PARAMS
EMBED_HIDDEN_DIM: 64
NUM_MLP_LAYERS: 0
NUM_EMBED_LAYERS: 0
MLP_HIDDEN_DIM: 256
AGENT_RNN_DIM: 256
ACTIVATION: 'relu'
NUM_Q_LAYERS: 2
NORM_TYPE: 'layer_norm'
NORM_QFN: 'layer_norm'

# LEARN PARAMS
BATCH_SIZE: 2048  # num_env=32
TRAINING_INTERVAL: 64
NUM_EPOCHS: 4
NUM_MINIBATCHES: 16

# epsilon-greedy
FIXED_EPSILON: 2 # range of epsilons
EPSILON_START: 1.0
EPSILON_FINISH: 0.1
EPSILON_ANNEAL_TIME: null

# ALGOO
LR: 0.0001
MAX_GRAD_NORM: 10
LR_LINEAR_DECAY: True
REW_SCALE: 0.1
EPS_ADAM: 0.00001

GAMMA: 0.99
LAMBDA: 0.95
